/*
 * generated by Xtext 2.33.0
 */
package org.xtext.liveprobes.liveagent.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.liveprobes.liveagent.ui.internal.LiveagentActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CfgExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(LiveagentActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		LiveagentActivator activator = LiveagentActivator.getInstance();
		return activator != null ? activator.getInjector(LiveagentActivator.ORG_XTEXT_LIVEPROBES_LIVEAGENT_CFG) : null;
	}

}
