/*
 * generated by Xtext 2.33.0
 */
package org.xtext.liveprobes.liveagent.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CfgUiModule extends AbstractCfgUiModule {

	public CfgUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
