/*
 * generated by Xtext 2.33.0
 */
package org.xtext.liveprobes.liveagent.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.liveprobes.liveagent.CfgRuntimeModule;
import org.xtext.liveprobes.liveagent.CfgStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CfgIdeSetup extends CfgStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CfgRuntimeModule(), new CfgIdeModule()));
	}
	
}
