/*
 * generated by Xtext 2.33.0
 */
grammar InternalCfg;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package org.xtext.liveprobes.liveagent.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package org.xtext.liveprobes.liveagent.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import org.xtext.liveprobes.liveagent.services.CfgGrammarAccess;

}

@parser::members {

 	private CfgGrammarAccess grammarAccess;

    public InternalCfgParser(TokenStream input, CfgGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "AgentConfig";
   	}

   	@Override
   	protected CfgGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleAgentConfig
entryRuleAgentConfig returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAgentConfigRule()); }
	iv_ruleAgentConfig=ruleAgentConfig
	{ $current=$iv_ruleAgentConfig.current; }
	EOF;

// Rule AgentConfig
ruleAgentConfig returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='AgentConfig'
		{
			newLeafNode(otherlv_0, grammarAccess.getAgentConfigAccess().getAgentConfigKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getAgentConfigAccess().getLeftCurlyBracketKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAgentConfigAccess().getConfigConfigurationParserRuleCall_2_0());
				}
				lv_config_2_0=ruleConfiguration
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAgentConfigRule());
					}
					set(
						$current,
						"config",
						lv_config_2_0,
						"org.xtext.liveprobes.liveagent.Cfg.Configuration");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='}'
		{
			newLeafNode(otherlv_3, grammarAccess.getAgentConfigAccess().getRightCurlyBracketKeyword_3());
		}
	)
;

// Entry rule entryRuleConfiguration
entryRuleConfiguration returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getConfigurationRule()); }
	iv_ruleConfiguration=ruleConfiguration
	{ $current=$iv_ruleConfiguration.current; }
	EOF;

// Rule Configuration
ruleConfiguration returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Language'
		{
			newLeafNode(otherlv_0, grammarAccess.getConfigurationAccess().getLanguageKeyword_0());
		}
		otherlv_1='='
		{
			newLeafNode(otherlv_1, grammarAccess.getConfigurationAccess().getEqualsSignKeyword_1());
		}
		(
			(
				lv_language_2_0=RULE_STRING
				{
					newLeafNode(lv_language_2_0, grammarAccess.getConfigurationAccess().getLanguageSTRINGTerminalRuleCall_2_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getConfigurationRule());
					}
					setWithLastConsumed(
						$current,
						"language",
						lv_language_2_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_3='compile'
		{
			newLeafNode(otherlv_3, grammarAccess.getConfigurationAccess().getCompileKeyword_3());
		}
		otherlv_4='='
		{
			newLeafNode(otherlv_4, grammarAccess.getConfigurationAccess().getEqualsSignKeyword_4());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getConfigurationAccess().getCompileBOOLEANParserRuleCall_5_0());
				}
				lv_compile_5_0=ruleBOOLEAN
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getConfigurationRule());
					}
					set(
						$current,
						"compile",
						lv_compile_5_0,
						"org.xtext.liveprobes.liveagent.Cfg.BOOLEAN");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_6='compile_command'
		{
			newLeafNode(otherlv_6, grammarAccess.getConfigurationAccess().getCompile_commandKeyword_6());
		}
		otherlv_7='='
		{
			newLeafNode(otherlv_7, grammarAccess.getConfigurationAccess().getEqualsSignKeyword_7());
		}
		(
			(
				lv_command_8_0=RULE_STRING
				{
					newLeafNode(lv_command_8_0, grammarAccess.getConfigurationAccess().getCommandSTRINGTerminalRuleCall_8_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getConfigurationRule());
					}
					setWithLastConsumed(
						$current,
						"command",
						lv_command_8_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_9='runner_path'
		{
			newLeafNode(otherlv_9, grammarAccess.getConfigurationAccess().getRunner_pathKeyword_9());
		}
		otherlv_10='='
		{
			newLeafNode(otherlv_10, grammarAccess.getConfigurationAccess().getEqualsSignKeyword_10());
		}
		(
			(
				lv_path_11_0=RULE_STRING
				{
					newLeafNode(lv_path_11_0, grammarAccess.getConfigurationAccess().getPathSTRINGTerminalRuleCall_11_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getConfigurationRule());
					}
					setWithLastConsumed(
						$current,
						"path",
						lv_path_11_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_12='dap_server'
		{
			newLeafNode(otherlv_12, grammarAccess.getConfigurationAccess().getDap_serverKeyword_12());
		}
		otherlv_13='='
		{
			newLeafNode(otherlv_13, grammarAccess.getConfigurationAccess().getEqualsSignKeyword_13());
		}
		(
			(
				lv_dap_14_0=RULE_STRING
				{
					newLeafNode(lv_dap_14_0, grammarAccess.getConfigurationAccess().getDapSTRINGTerminalRuleCall_14_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getConfigurationRule());
					}
					setWithLastConsumed(
						$current,
						"dap",
						lv_dap_14_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_15='parser'
		{
			newLeafNode(otherlv_15, grammarAccess.getConfigurationAccess().getParserKeyword_15());
		}
		otherlv_16='='
		{
			newLeafNode(otherlv_16, grammarAccess.getConfigurationAccess().getEqualsSignKeyword_16());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getConfigurationAccess().getParserBOOLEANParserRuleCall_17_0());
				}
				lv_parser_17_0=ruleBOOLEAN
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getConfigurationRule());
					}
					set(
						$current,
						"parser",
						lv_parser_17_0,
						"org.xtext.liveprobes.liveagent.Cfg.BOOLEAN");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_18='IO_socket'
		{
			newLeafNode(otherlv_18, grammarAccess.getConfigurationAccess().getIO_socketKeyword_18());
		}
		otherlv_19='='
		{
			newLeafNode(otherlv_19, grammarAccess.getConfigurationAccess().getEqualsSignKeyword_19());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getConfigurationAccess().getIoBOOLEANParserRuleCall_20_0());
				}
				lv_io_20_0=ruleBOOLEAN
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getConfigurationRule());
					}
					set(
						$current,
						"io",
						lv_io_20_0,
						"org.xtext.liveprobes.liveagent.Cfg.BOOLEAN");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_21='thread_ID'
		{
			newLeafNode(otherlv_21, grammarAccess.getConfigurationAccess().getThread_IDKeyword_21());
		}
		otherlv_22='='
		{
			newLeafNode(otherlv_22, grammarAccess.getConfigurationAccess().getEqualsSignKeyword_22());
		}
		(
			(
				lv_thread_23_0=RULE_STRING
				{
					newLeafNode(lv_thread_23_0, grammarAccess.getConfigurationAccess().getThreadSTRINGTerminalRuleCall_23_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getConfigurationRule());
					}
					setWithLastConsumed(
						$current,
						"thread",
						lv_thread_23_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_24='adapter_ID'
		{
			newLeafNode(otherlv_24, grammarAccess.getConfigurationAccess().getAdapter_IDKeyword_24());
		}
		otherlv_25='='
		{
			newLeafNode(otherlv_25, grammarAccess.getConfigurationAccess().getEqualsSignKeyword_25());
		}
		(
			(
				lv_adapter_26_0=RULE_STRING
				{
					newLeafNode(lv_adapter_26_0, grammarAccess.getConfigurationAccess().getAdapterSTRINGTerminalRuleCall_26_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getConfigurationRule());
					}
					setWithLastConsumed(
						$current,
						"adapter",
						lv_adapter_26_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_27='runner_breakpoint'
		{
			newLeafNode(otherlv_27, grammarAccess.getConfigurationAccess().getRunner_breakpointKeyword_27());
		}
		otherlv_28='='
		{
			newLeafNode(otherlv_28, grammarAccess.getConfigurationAccess().getEqualsSignKeyword_28());
		}
		(
			(
				lv_breakpoint_29_0=RULE_STRING
				{
					newLeafNode(lv_breakpoint_29_0, grammarAccess.getConfigurationAccess().getBreakpointSTRINGTerminalRuleCall_29_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getConfigurationRule());
					}
					setWithLastConsumed(
						$current,
						"breakpoint",
						lv_breakpoint_29_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_30='load_command'
		{
			newLeafNode(otherlv_30, grammarAccess.getConfigurationAccess().getLoad_commandKeyword_30());
		}
		otherlv_31='='
		{
			newLeafNode(otherlv_31, grammarAccess.getConfigurationAccess().getEqualsSignKeyword_31());
		}
		(
			(
				lv_load_32_0=RULE_STRING
				{
					newLeafNode(lv_load_32_0, grammarAccess.getConfigurationAccess().getLoadSTRINGTerminalRuleCall_32_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getConfigurationRule());
					}
					setWithLastConsumed(
						$current,
						"load",
						lv_load_32_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_33='execute_command'
		{
			newLeafNode(otherlv_33, grammarAccess.getConfigurationAccess().getExecute_commandKeyword_33());
		}
		otherlv_34='='
		{
			newLeafNode(otherlv_34, grammarAccess.getConfigurationAccess().getEqualsSignKeyword_34());
		}
		(
			(
				lv_exec_35_0=RULE_STRING
				{
					newLeafNode(lv_exec_35_0, grammarAccess.getConfigurationAccess().getExecSTRINGTerminalRuleCall_35_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getConfigurationRule());
					}
					setWithLastConsumed(
						$current,
						"exec",
						lv_exec_35_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getConfigurationAccess().getAdditionalConfigBoolParserRuleCall_36_0_0());
					}
					lv_additionalConfig_36_1=ruleBool
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getConfigurationRule());
						}
						add(
							$current,
							"additionalConfig",
							lv_additionalConfig_36_1,
							"org.xtext.liveprobes.liveagent.Cfg.Bool");
						afterParserOrEnumRuleCall();
					}
					    |
					{
						newCompositeNode(grammarAccess.getConfigurationAccess().getAdditionalConfigLineParserRuleCall_36_0_1());
					}
					lv_additionalConfig_36_2=ruleLine
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getConfigurationRule());
						}
						add(
							$current,
							"additionalConfig",
							lv_additionalConfig_36_2,
							"org.xtext.liveprobes.liveagent.Cfg.Line");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
	)
;

// Entry rule entryRuleBool
entryRuleBool returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getBoolRule()); }
	iv_ruleBool=ruleBool
	{ $current=$iv_ruleBool.current; }
	EOF;

// Rule Bool
ruleBool returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='cfg'
		{
			newLeafNode(otherlv_0, grammarAccess.getBoolAccess().getCfgKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getBoolAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getBoolRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='='
		{
			newLeafNode(otherlv_2, grammarAccess.getBoolAccess().getEqualsSignKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getBoolAccess().getValueBOOLEANParserRuleCall_3_0());
				}
				lv_value_3_0=ruleBOOLEAN
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getBoolRule());
					}
					set(
						$current,
						"value",
						lv_value_3_0,
						"org.xtext.liveprobes.liveagent.Cfg.BOOLEAN");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleLine
entryRuleLine returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getLineRule()); }
	iv_ruleLine=ruleLine
	{ $current=$iv_ruleLine.current; }
	EOF;

// Rule Line
ruleLine returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='cfg'
		{
			newLeafNode(otherlv_0, grammarAccess.getLineAccess().getCfgKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getLineAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getLineRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='='
		{
			newLeafNode(otherlv_2, grammarAccess.getLineAccess().getEqualsSignKeyword_2());
		}
		(
			(
				lv_value_3_0=RULE_STRING
				{
					newLeafNode(lv_value_3_0, grammarAccess.getLineAccess().getValueSTRINGTerminalRuleCall_3_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getLineRule());
					}
					setWithLastConsumed(
						$current,
						"value",
						lv_value_3_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
	)
;

// Entry rule entryRuleBOOLEAN
entryRuleBOOLEAN returns [String current=null]:
	{ newCompositeNode(grammarAccess.getBOOLEANRule()); }
	iv_ruleBOOLEAN=ruleBOOLEAN
	{ $current=$iv_ruleBOOLEAN.current.getText(); }
	EOF;

// Rule BOOLEAN
ruleBOOLEAN returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		kw='True'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getBOOLEANAccess().getTrueKeyword_0());
		}
		    |
		kw='False'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getBOOLEANAccess().getFalseKeyword_1());
		}
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
