/*
 * generated by Xtext 2.33.0
 */
package org.xtext.liveprobes.liveagent;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CfgStandaloneSetup extends CfgStandaloneSetupGenerated {

	public static void doSetup() {
		new CfgStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
