/*
 * generated by Xtext 2.33.0
 */
grammar InternalCfg;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package org.xtext.liveprobes.liveagent.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package org.xtext.liveprobes.liveagent.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import org.xtext.liveprobes.liveagent.services.CfgGrammarAccess;

}
@parser::members {
	private CfgGrammarAccess grammarAccess;

	public void setGrammarAccess(CfgGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleAgentConfig
entryRuleAgentConfig
:
{ before(grammarAccess.getAgentConfigRule()); }
	 ruleAgentConfig
{ after(grammarAccess.getAgentConfigRule()); } 
	 EOF 
;

// Rule AgentConfig
ruleAgentConfig 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getAgentConfigAccess().getGroup()); }
		(rule__AgentConfig__Group__0)
		{ after(grammarAccess.getAgentConfigAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleConfiguration
entryRuleConfiguration
:
{ before(grammarAccess.getConfigurationRule()); }
	 ruleConfiguration
{ after(grammarAccess.getConfigurationRule()); } 
	 EOF 
;

// Rule Configuration
ruleConfiguration 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getConfigurationAccess().getGroup()); }
		(rule__Configuration__Group__0)
		{ after(grammarAccess.getConfigurationAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleBool
entryRuleBool
:
{ before(grammarAccess.getBoolRule()); }
	 ruleBool
{ after(grammarAccess.getBoolRule()); } 
	 EOF 
;

// Rule Bool
ruleBool 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getBoolAccess().getGroup()); }
		(rule__Bool__Group__0)
		{ after(grammarAccess.getBoolAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleLine
entryRuleLine
:
{ before(grammarAccess.getLineRule()); }
	 ruleLine
{ after(grammarAccess.getLineRule()); } 
	 EOF 
;

// Rule Line
ruleLine 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getLineAccess().getGroup()); }
		(rule__Line__Group__0)
		{ after(grammarAccess.getLineAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleBOOLEAN
entryRuleBOOLEAN
:
{ before(grammarAccess.getBOOLEANRule()); }
	 ruleBOOLEAN
{ after(grammarAccess.getBOOLEANRule()); } 
	 EOF 
;

// Rule BOOLEAN
ruleBOOLEAN 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getBOOLEANAccess().getAlternatives()); }
		(rule__BOOLEAN__Alternatives)
		{ after(grammarAccess.getBOOLEANAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__AdditionalConfigAlternatives_36_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigurationAccess().getAdditionalConfigBoolParserRuleCall_36_0_0()); }
		ruleBool
		{ after(grammarAccess.getConfigurationAccess().getAdditionalConfigBoolParserRuleCall_36_0_0()); }
	)
	|
	(
		{ before(grammarAccess.getConfigurationAccess().getAdditionalConfigLineParserRuleCall_36_0_1()); }
		ruleLine
		{ after(grammarAccess.getConfigurationAccess().getAdditionalConfigLineParserRuleCall_36_0_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__BOOLEAN__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBOOLEANAccess().getTrueKeyword_0()); }
		'True'
		{ after(grammarAccess.getBOOLEANAccess().getTrueKeyword_0()); }
	)
	|
	(
		{ before(grammarAccess.getBOOLEANAccess().getFalseKeyword_1()); }
		'False'
		{ after(grammarAccess.getBOOLEANAccess().getFalseKeyword_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AgentConfig__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AgentConfig__Group__0__Impl
	rule__AgentConfig__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__AgentConfig__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAgentConfigAccess().getAgentConfigKeyword_0()); }
	'AgentConfig'
	{ after(grammarAccess.getAgentConfigAccess().getAgentConfigKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AgentConfig__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AgentConfig__Group__1__Impl
	rule__AgentConfig__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__AgentConfig__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAgentConfigAccess().getLeftCurlyBracketKeyword_1()); }
	'{'
	{ after(grammarAccess.getAgentConfigAccess().getLeftCurlyBracketKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AgentConfig__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AgentConfig__Group__2__Impl
	rule__AgentConfig__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__AgentConfig__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAgentConfigAccess().getConfigAssignment_2()); }
	(rule__AgentConfig__ConfigAssignment_2)
	{ after(grammarAccess.getAgentConfigAccess().getConfigAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AgentConfig__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AgentConfig__Group__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__AgentConfig__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAgentConfigAccess().getRightCurlyBracketKeyword_3()); }
	'}'
	{ after(grammarAccess.getAgentConfigAccess().getRightCurlyBracketKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Configuration__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__0__Impl
	rule__Configuration__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getLanguageKeyword_0()); }
	'Language'
	{ after(grammarAccess.getConfigurationAccess().getLanguageKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__1__Impl
	rule__Configuration__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_1()); }
	'='
	{ after(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__2__Impl
	rule__Configuration__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getLanguageAssignment_2()); }
	(rule__Configuration__LanguageAssignment_2)
	{ after(grammarAccess.getConfigurationAccess().getLanguageAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__3__Impl
	rule__Configuration__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getCompileKeyword_3()); }
	'compile'
	{ after(grammarAccess.getConfigurationAccess().getCompileKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__4__Impl
	rule__Configuration__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_4()); }
	'='
	{ after(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__5__Impl
	rule__Configuration__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getCompileAssignment_5()); }
	(rule__Configuration__CompileAssignment_5)
	{ after(grammarAccess.getConfigurationAccess().getCompileAssignment_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__6__Impl
	rule__Configuration__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getCompile_commandKeyword_6()); }
	'compile_command'
	{ after(grammarAccess.getConfigurationAccess().getCompile_commandKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__7__Impl
	rule__Configuration__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_7()); }
	'='
	{ after(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__8__Impl
	rule__Configuration__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getCommandAssignment_8()); }
	(rule__Configuration__CommandAssignment_8)
	{ after(grammarAccess.getConfigurationAccess().getCommandAssignment_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__9__Impl
	rule__Configuration__Group__10
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getRunner_pathKeyword_9()); }
	'runner_path'
	{ after(grammarAccess.getConfigurationAccess().getRunner_pathKeyword_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__10
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__10__Impl
	rule__Configuration__Group__11
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__10__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_10()); }
	'='
	{ after(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_10()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__11
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__11__Impl
	rule__Configuration__Group__12
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__11__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getPathAssignment_11()); }
	(rule__Configuration__PathAssignment_11)
	{ after(grammarAccess.getConfigurationAccess().getPathAssignment_11()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__12
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__12__Impl
	rule__Configuration__Group__13
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__12__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getDap_serverKeyword_12()); }
	'dap_server'
	{ after(grammarAccess.getConfigurationAccess().getDap_serverKeyword_12()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__13
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__13__Impl
	rule__Configuration__Group__14
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__13__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_13()); }
	'='
	{ after(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_13()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__14
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__14__Impl
	rule__Configuration__Group__15
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__14__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getDapAssignment_14()); }
	(rule__Configuration__DapAssignment_14)
	{ after(grammarAccess.getConfigurationAccess().getDapAssignment_14()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__15
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__15__Impl
	rule__Configuration__Group__16
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__15__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getParserKeyword_15()); }
	'parser'
	{ after(grammarAccess.getConfigurationAccess().getParserKeyword_15()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__16
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__16__Impl
	rule__Configuration__Group__17
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__16__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_16()); }
	'='
	{ after(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_16()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__17
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__17__Impl
	rule__Configuration__Group__18
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__17__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getParserAssignment_17()); }
	(rule__Configuration__ParserAssignment_17)
	{ after(grammarAccess.getConfigurationAccess().getParserAssignment_17()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__18
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__18__Impl
	rule__Configuration__Group__19
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__18__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getIO_socketKeyword_18()); }
	'IO_socket'
	{ after(grammarAccess.getConfigurationAccess().getIO_socketKeyword_18()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__19
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__19__Impl
	rule__Configuration__Group__20
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__19__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_19()); }
	'='
	{ after(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_19()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__20
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__20__Impl
	rule__Configuration__Group__21
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__20__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getIoAssignment_20()); }
	(rule__Configuration__IoAssignment_20)
	{ after(grammarAccess.getConfigurationAccess().getIoAssignment_20()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__21
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__21__Impl
	rule__Configuration__Group__22
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__21__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getThread_IDKeyword_21()); }
	'thread_ID'
	{ after(grammarAccess.getConfigurationAccess().getThread_IDKeyword_21()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__22
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__22__Impl
	rule__Configuration__Group__23
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__22__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_22()); }
	'='
	{ after(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_22()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__23
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__23__Impl
	rule__Configuration__Group__24
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__23__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getThreadAssignment_23()); }
	(rule__Configuration__ThreadAssignment_23)
	{ after(grammarAccess.getConfigurationAccess().getThreadAssignment_23()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__24
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__24__Impl
	rule__Configuration__Group__25
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__24__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getAdapter_IDKeyword_24()); }
	'adapter_ID'
	{ after(grammarAccess.getConfigurationAccess().getAdapter_IDKeyword_24()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__25
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__25__Impl
	rule__Configuration__Group__26
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__25__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_25()); }
	'='
	{ after(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_25()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__26
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__26__Impl
	rule__Configuration__Group__27
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__26__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getAdapterAssignment_26()); }
	(rule__Configuration__AdapterAssignment_26)
	{ after(grammarAccess.getConfigurationAccess().getAdapterAssignment_26()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__27
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__27__Impl
	rule__Configuration__Group__28
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__27__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getRunner_breakpointKeyword_27()); }
	'runner_breakpoint'
	{ after(grammarAccess.getConfigurationAccess().getRunner_breakpointKeyword_27()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__28
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__28__Impl
	rule__Configuration__Group__29
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__28__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_28()); }
	'='
	{ after(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_28()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__29
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__29__Impl
	rule__Configuration__Group__30
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__29__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getBreakpointAssignment_29()); }
	(rule__Configuration__BreakpointAssignment_29)
	{ after(grammarAccess.getConfigurationAccess().getBreakpointAssignment_29()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__30
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__30__Impl
	rule__Configuration__Group__31
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__30__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getLoad_commandKeyword_30()); }
	'load_command'
	{ after(grammarAccess.getConfigurationAccess().getLoad_commandKeyword_30()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__31
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__31__Impl
	rule__Configuration__Group__32
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__31__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_31()); }
	'='
	{ after(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_31()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__32
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__32__Impl
	rule__Configuration__Group__33
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__32__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getLoadAssignment_32()); }
	(rule__Configuration__LoadAssignment_32)
	{ after(grammarAccess.getConfigurationAccess().getLoadAssignment_32()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__33
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__33__Impl
	rule__Configuration__Group__34
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__33__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getExecute_commandKeyword_33()); }
	'execute_command'
	{ after(grammarAccess.getConfigurationAccess().getExecute_commandKeyword_33()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__34
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__34__Impl
	rule__Configuration__Group__35
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__34__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_34()); }
	'='
	{ after(grammarAccess.getConfigurationAccess().getEqualsSignKeyword_34()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__35
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__35__Impl
	rule__Configuration__Group__36
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__35__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getExecAssignment_35()); }
	(rule__Configuration__ExecAssignment_35)
	{ after(grammarAccess.getConfigurationAccess().getExecAssignment_35()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__36
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Configuration__Group__36__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__Group__36__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigurationAccess().getAdditionalConfigAssignment_36()); }
	(rule__Configuration__AdditionalConfigAssignment_36)*
	{ after(grammarAccess.getConfigurationAccess().getAdditionalConfigAssignment_36()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Bool__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Bool__Group__0__Impl
	rule__Bool__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Bool__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolAccess().getCfgKeyword_0()); }
	'cfg'
	{ after(grammarAccess.getBoolAccess().getCfgKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Bool__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Bool__Group__1__Impl
	rule__Bool__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Bool__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolAccess().getNameAssignment_1()); }
	(rule__Bool__NameAssignment_1)
	{ after(grammarAccess.getBoolAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Bool__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Bool__Group__2__Impl
	rule__Bool__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Bool__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolAccess().getEqualsSignKeyword_2()); }
	'='
	{ after(grammarAccess.getBoolAccess().getEqualsSignKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Bool__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Bool__Group__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Bool__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolAccess().getValueAssignment_3()); }
	(rule__Bool__ValueAssignment_3)
	{ after(grammarAccess.getBoolAccess().getValueAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Line__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Line__Group__0__Impl
	rule__Line__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Line__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLineAccess().getCfgKeyword_0()); }
	'cfg'
	{ after(grammarAccess.getLineAccess().getCfgKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Line__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Line__Group__1__Impl
	rule__Line__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Line__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLineAccess().getNameAssignment_1()); }
	(rule__Line__NameAssignment_1)
	{ after(grammarAccess.getLineAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Line__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Line__Group__2__Impl
	rule__Line__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Line__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLineAccess().getEqualsSignKeyword_2()); }
	'='
	{ after(grammarAccess.getLineAccess().getEqualsSignKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Line__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Line__Group__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Line__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLineAccess().getValueAssignment_3()); }
	(rule__Line__ValueAssignment_3)
	{ after(grammarAccess.getLineAccess().getValueAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__AgentConfig__ConfigAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAgentConfigAccess().getConfigConfigurationParserRuleCall_2_0()); }
		ruleConfiguration
		{ after(grammarAccess.getAgentConfigAccess().getConfigConfigurationParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__LanguageAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigurationAccess().getLanguageSTRINGTerminalRuleCall_2_0()); }
		RULE_STRING
		{ after(grammarAccess.getConfigurationAccess().getLanguageSTRINGTerminalRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__CompileAssignment_5
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigurationAccess().getCompileBOOLEANParserRuleCall_5_0()); }
		ruleBOOLEAN
		{ after(grammarAccess.getConfigurationAccess().getCompileBOOLEANParserRuleCall_5_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__CommandAssignment_8
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigurationAccess().getCommandSTRINGTerminalRuleCall_8_0()); }
		RULE_STRING
		{ after(grammarAccess.getConfigurationAccess().getCommandSTRINGTerminalRuleCall_8_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__PathAssignment_11
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigurationAccess().getPathSTRINGTerminalRuleCall_11_0()); }
		RULE_STRING
		{ after(grammarAccess.getConfigurationAccess().getPathSTRINGTerminalRuleCall_11_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__DapAssignment_14
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigurationAccess().getDapSTRINGTerminalRuleCall_14_0()); }
		RULE_STRING
		{ after(grammarAccess.getConfigurationAccess().getDapSTRINGTerminalRuleCall_14_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__ParserAssignment_17
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigurationAccess().getParserBOOLEANParserRuleCall_17_0()); }
		ruleBOOLEAN
		{ after(grammarAccess.getConfigurationAccess().getParserBOOLEANParserRuleCall_17_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__IoAssignment_20
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigurationAccess().getIoBOOLEANParserRuleCall_20_0()); }
		ruleBOOLEAN
		{ after(grammarAccess.getConfigurationAccess().getIoBOOLEANParserRuleCall_20_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__ThreadAssignment_23
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigurationAccess().getThreadSTRINGTerminalRuleCall_23_0()); }
		RULE_STRING
		{ after(grammarAccess.getConfigurationAccess().getThreadSTRINGTerminalRuleCall_23_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__AdapterAssignment_26
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigurationAccess().getAdapterSTRINGTerminalRuleCall_26_0()); }
		RULE_STRING
		{ after(grammarAccess.getConfigurationAccess().getAdapterSTRINGTerminalRuleCall_26_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__BreakpointAssignment_29
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigurationAccess().getBreakpointSTRINGTerminalRuleCall_29_0()); }
		RULE_STRING
		{ after(grammarAccess.getConfigurationAccess().getBreakpointSTRINGTerminalRuleCall_29_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__LoadAssignment_32
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigurationAccess().getLoadSTRINGTerminalRuleCall_32_0()); }
		RULE_STRING
		{ after(grammarAccess.getConfigurationAccess().getLoadSTRINGTerminalRuleCall_32_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__ExecAssignment_35
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigurationAccess().getExecSTRINGTerminalRuleCall_35_0()); }
		RULE_STRING
		{ after(grammarAccess.getConfigurationAccess().getExecSTRINGTerminalRuleCall_35_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Configuration__AdditionalConfigAssignment_36
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigurationAccess().getAdditionalConfigAlternatives_36_0()); }
		(rule__Configuration__AdditionalConfigAlternatives_36_0)
		{ after(grammarAccess.getConfigurationAccess().getAdditionalConfigAlternatives_36_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Bool__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBoolAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getBoolAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Bool__ValueAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBoolAccess().getValueBOOLEANParserRuleCall_3_0()); }
		ruleBOOLEAN
		{ after(grammarAccess.getBoolAccess().getValueBOOLEANParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Line__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLineAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getLineAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Line__ValueAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLineAccess().getValueSTRINGTerminalRuleCall_3_0()); }
		RULE_STRING
		{ after(grammarAccess.getLineAccess().getValueSTRINGTerminalRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
