/*
 * generated by Xtext 2.33.0
 */
package org.xtext.liveprobes.liveagent.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class CfgScopeProvider extends AbstractCfgScopeProvider {

}
