/*
 * generated by Xtext 2.33.0
 */
package org.xtext.liveprobes.liveagent.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.liveprobes.liveagent.ui.internal.LiveagentActivator;

public class CfgUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LiveagentActivator.getInstance().getInjector("org.xtext.liveprobes.liveagent.Cfg");
	}

}
