/*
 * generated by Xtext 2.33.0
 */
package org.xtext.liveprobes.liveagent.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CfgAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/liveprobes/liveagent/parser/antlr/internal/InternalCfg.tokens");
	}
}
