/*
 * generated by Xtext 2.33.0
 */
package org.xtext.liveprobes.liveagent.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.liveprobes.liveagent.parser.antlr.internal.InternalCfgParser;
import org.xtext.liveprobes.liveagent.services.CfgGrammarAccess;

public class CfgParser extends AbstractAntlrParser {

	@Inject
	private CfgGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCfgParser createParser(XtextTokenStream stream) {
		return new InternalCfgParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "AgentConfig";
	}

	public CfgGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CfgGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
