/*
 * generated by Xtext 2.33.0
 */
package org.xtext.liveprobes.liveagent.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class CfgProposalProvider extends AbstractCfgProposalProvider {
}
