/**
 * generated by Xtext 2.33.0
 */
package org.xtext.liveprobes.liveagent.cfg;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Agent Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.liveprobes.liveagent.cfg.AgentConfig#getConfig <em>Config</em>}</li>
 * </ul>
 *
 * @see org.xtext.liveprobes.liveagent.cfg.CfgPackage#getAgentConfig()
 * @model
 * @generated
 */
public interface AgentConfig extends EObject
{
  /**
   * Returns the value of the '<em><b>Config</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Config</em>' containment reference.
   * @see #setConfig(Configuration)
   * @see org.xtext.liveprobes.liveagent.cfg.CfgPackage#getAgentConfig_Config()
   * @model containment="true"
   * @generated
   */
  Configuration getConfig();

  /**
   * Sets the value of the '{@link org.xtext.liveprobes.liveagent.cfg.AgentConfig#getConfig <em>Config</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Config</em>' containment reference.
   * @see #getConfig()
   * @generated
   */
  void setConfig(Configuration value);

} // AgentConfig
