/**
 * generated by Xtext 2.33.0
 */
package org.xtext.liveprobes.liveagent.cfg;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.liveprobes.liveagent.cfg.CfgFactory
 * @model kind="package"
 * @generated
 */
public interface CfgPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cfg";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/liveprobes/liveagent/Cfg";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cfg";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CfgPackage eINSTANCE = org.xtext.liveprobes.liveagent.cfg.impl.CfgPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.liveprobes.liveagent.cfg.impl.AgentConfigImpl <em>Agent Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.liveprobes.liveagent.cfg.impl.AgentConfigImpl
   * @see org.xtext.liveprobes.liveagent.cfg.impl.CfgPackageImpl#getAgentConfig()
   * @generated
   */
  int AGENT_CONFIG = 0;

  /**
   * The feature id for the '<em><b>Config</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT_CONFIG__CONFIG = 0;

  /**
   * The number of structural features of the '<em>Agent Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT_CONFIG_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.liveprobes.liveagent.cfg.impl.ConfigurationImpl <em>Configuration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.liveprobes.liveagent.cfg.impl.ConfigurationImpl
   * @see org.xtext.liveprobes.liveagent.cfg.impl.CfgPackageImpl#getConfiguration()
   * @generated
   */
  int CONFIGURATION = 1;

  /**
   * The feature id for the '<em><b>Language</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__LANGUAGE = 0;

  /**
   * The feature id for the '<em><b>Compile</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__COMPILE = 1;

  /**
   * The feature id for the '<em><b>Command</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__COMMAND = 2;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__PATH = 3;

  /**
   * The feature id for the '<em><b>Dap</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__DAP = 4;

  /**
   * The feature id for the '<em><b>Parser</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__PARSER = 5;

  /**
   * The feature id for the '<em><b>Io</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__IO = 6;

  /**
   * The feature id for the '<em><b>Thread</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__THREAD = 7;

  /**
   * The feature id for the '<em><b>Adapter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__ADAPTER = 8;

  /**
   * The feature id for the '<em><b>Breakpoint</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__BREAKPOINT = 9;

  /**
   * The feature id for the '<em><b>Load</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__LOAD = 10;

  /**
   * The feature id for the '<em><b>Exec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__EXEC = 11;

  /**
   * The feature id for the '<em><b>Additional Config</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__ADDITIONAL_CONFIG = 12;

  /**
   * The number of structural features of the '<em>Configuration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION_FEATURE_COUNT = 13;

  /**
   * The meta object id for the '{@link org.xtext.liveprobes.liveagent.cfg.impl.BoolImpl <em>Bool</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.liveprobes.liveagent.cfg.impl.BoolImpl
   * @see org.xtext.liveprobes.liveagent.cfg.impl.CfgPackageImpl#getBool()
   * @generated
   */
  int BOOL = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL__VALUE = 1;

  /**
   * The number of structural features of the '<em>Bool</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.liveprobes.liveagent.cfg.impl.LineImpl <em>Line</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.liveprobes.liveagent.cfg.impl.LineImpl
   * @see org.xtext.liveprobes.liveagent.cfg.impl.CfgPackageImpl#getLine()
   * @generated
   */
  int LINE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE__VALUE = 1;

  /**
   * The number of structural features of the '<em>Line</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.liveprobes.liveagent.cfg.AgentConfig <em>Agent Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Agent Config</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.AgentConfig
   * @generated
   */
  EClass getAgentConfig();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.liveprobes.liveagent.cfg.AgentConfig#getConfig <em>Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Config</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.AgentConfig#getConfig()
   * @see #getAgentConfig()
   * @generated
   */
  EReference getAgentConfig_Config();

  /**
   * Returns the meta object for class '{@link org.xtext.liveprobes.liveagent.cfg.Configuration <em>Configuration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Configuration</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Configuration
   * @generated
   */
  EClass getConfiguration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getLanguage <em>Language</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Language</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Configuration#getLanguage()
   * @see #getConfiguration()
   * @generated
   */
  EAttribute getConfiguration_Language();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getCompile <em>Compile</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Compile</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Configuration#getCompile()
   * @see #getConfiguration()
   * @generated
   */
  EAttribute getConfiguration_Compile();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Command</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Configuration#getCommand()
   * @see #getConfiguration()
   * @generated
   */
  EAttribute getConfiguration_Command();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Configuration#getPath()
   * @see #getConfiguration()
   * @generated
   */
  EAttribute getConfiguration_Path();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getDap <em>Dap</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dap</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Configuration#getDap()
   * @see #getConfiguration()
   * @generated
   */
  EAttribute getConfiguration_Dap();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getParser <em>Parser</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Parser</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Configuration#getParser()
   * @see #getConfiguration()
   * @generated
   */
  EAttribute getConfiguration_Parser();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getIo <em>Io</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Io</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Configuration#getIo()
   * @see #getConfiguration()
   * @generated
   */
  EAttribute getConfiguration_Io();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getThread <em>Thread</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Thread</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Configuration#getThread()
   * @see #getConfiguration()
   * @generated
   */
  EAttribute getConfiguration_Thread();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getAdapter <em>Adapter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Adapter</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Configuration#getAdapter()
   * @see #getConfiguration()
   * @generated
   */
  EAttribute getConfiguration_Adapter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getBreakpoint <em>Breakpoint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Breakpoint</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Configuration#getBreakpoint()
   * @see #getConfiguration()
   * @generated
   */
  EAttribute getConfiguration_Breakpoint();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getLoad <em>Load</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Load</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Configuration#getLoad()
   * @see #getConfiguration()
   * @generated
   */
  EAttribute getConfiguration_Load();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getExec <em>Exec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Exec</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Configuration#getExec()
   * @see #getConfiguration()
   * @generated
   */
  EAttribute getConfiguration_Exec();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getAdditionalConfig <em>Additional Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Additional Config</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Configuration#getAdditionalConfig()
   * @see #getConfiguration()
   * @generated
   */
  EReference getConfiguration_AdditionalConfig();

  /**
   * Returns the meta object for class '{@link org.xtext.liveprobes.liveagent.cfg.Bool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Bool
   * @generated
   */
  EClass getBool();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.liveprobes.liveagent.cfg.Bool#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Bool#getName()
   * @see #getBool()
   * @generated
   */
  EAttribute getBool_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.liveprobes.liveagent.cfg.Bool#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Bool#getValue()
   * @see #getBool()
   * @generated
   */
  EAttribute getBool_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.liveprobes.liveagent.cfg.Line <em>Line</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Line</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Line
   * @generated
   */
  EClass getLine();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.liveprobes.liveagent.cfg.Line#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Line#getName()
   * @see #getLine()
   * @generated
   */
  EAttribute getLine_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.liveprobes.liveagent.cfg.Line#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.liveprobes.liveagent.cfg.Line#getValue()
   * @see #getLine()
   * @generated
   */
  EAttribute getLine_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CfgFactory getCfgFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.liveprobes.liveagent.cfg.impl.AgentConfigImpl <em>Agent Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.liveprobes.liveagent.cfg.impl.AgentConfigImpl
     * @see org.xtext.liveprobes.liveagent.cfg.impl.CfgPackageImpl#getAgentConfig()
     * @generated
     */
    EClass AGENT_CONFIG = eINSTANCE.getAgentConfig();

    /**
     * The meta object literal for the '<em><b>Config</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AGENT_CONFIG__CONFIG = eINSTANCE.getAgentConfig_Config();

    /**
     * The meta object literal for the '{@link org.xtext.liveprobes.liveagent.cfg.impl.ConfigurationImpl <em>Configuration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.liveprobes.liveagent.cfg.impl.ConfigurationImpl
     * @see org.xtext.liveprobes.liveagent.cfg.impl.CfgPackageImpl#getConfiguration()
     * @generated
     */
    EClass CONFIGURATION = eINSTANCE.getConfiguration();

    /**
     * The meta object literal for the '<em><b>Language</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION__LANGUAGE = eINSTANCE.getConfiguration_Language();

    /**
     * The meta object literal for the '<em><b>Compile</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION__COMPILE = eINSTANCE.getConfiguration_Compile();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION__COMMAND = eINSTANCE.getConfiguration_Command();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION__PATH = eINSTANCE.getConfiguration_Path();

    /**
     * The meta object literal for the '<em><b>Dap</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION__DAP = eINSTANCE.getConfiguration_Dap();

    /**
     * The meta object literal for the '<em><b>Parser</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION__PARSER = eINSTANCE.getConfiguration_Parser();

    /**
     * The meta object literal for the '<em><b>Io</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION__IO = eINSTANCE.getConfiguration_Io();

    /**
     * The meta object literal for the '<em><b>Thread</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION__THREAD = eINSTANCE.getConfiguration_Thread();

    /**
     * The meta object literal for the '<em><b>Adapter</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION__ADAPTER = eINSTANCE.getConfiguration_Adapter();

    /**
     * The meta object literal for the '<em><b>Breakpoint</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION__BREAKPOINT = eINSTANCE.getConfiguration_Breakpoint();

    /**
     * The meta object literal for the '<em><b>Load</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION__LOAD = eINSTANCE.getConfiguration_Load();

    /**
     * The meta object literal for the '<em><b>Exec</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION__EXEC = eINSTANCE.getConfiguration_Exec();

    /**
     * The meta object literal for the '<em><b>Additional Config</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIGURATION__ADDITIONAL_CONFIG = eINSTANCE.getConfiguration_AdditionalConfig();

    /**
     * The meta object literal for the '{@link org.xtext.liveprobes.liveagent.cfg.impl.BoolImpl <em>Bool</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.liveprobes.liveagent.cfg.impl.BoolImpl
     * @see org.xtext.liveprobes.liveagent.cfg.impl.CfgPackageImpl#getBool()
     * @generated
     */
    EClass BOOL = eINSTANCE.getBool();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOL__NAME = eINSTANCE.getBool_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOL__VALUE = eINSTANCE.getBool_Value();

    /**
     * The meta object literal for the '{@link org.xtext.liveprobes.liveagent.cfg.impl.LineImpl <em>Line</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.liveprobes.liveagent.cfg.impl.LineImpl
     * @see org.xtext.liveprobes.liveagent.cfg.impl.CfgPackageImpl#getLine()
     * @generated
     */
    EClass LINE = eINSTANCE.getLine();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINE__NAME = eINSTANCE.getLine_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINE__VALUE = eINSTANCE.getLine_Value();

  }

} //CfgPackage
