/**
 * generated by Xtext 2.33.0
 */
package org.xtext.liveprobes.liveagent.cfg;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Configuration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getLanguage <em>Language</em>}</li>
 *   <li>{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getCompile <em>Compile</em>}</li>
 *   <li>{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getCommand <em>Command</em>}</li>
 *   <li>{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getPath <em>Path</em>}</li>
 *   <li>{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getDap <em>Dap</em>}</li>
 *   <li>{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getParser <em>Parser</em>}</li>
 *   <li>{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getIo <em>Io</em>}</li>
 *   <li>{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getThread <em>Thread</em>}</li>
 *   <li>{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getAdapter <em>Adapter</em>}</li>
 *   <li>{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getBreakpoint <em>Breakpoint</em>}</li>
 *   <li>{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getLoad <em>Load</em>}</li>
 *   <li>{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getExec <em>Exec</em>}</li>
 *   <li>{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getAdditionalConfig <em>Additional Config</em>}</li>
 * </ul>
 *
 * @see org.xtext.liveprobes.liveagent.cfg.CfgPackage#getConfiguration()
 * @model
 * @generated
 */
public interface Configuration extends EObject
{
  /**
   * Returns the value of the '<em><b>Language</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Language</em>' attribute.
   * @see #setLanguage(String)
   * @see org.xtext.liveprobes.liveagent.cfg.CfgPackage#getConfiguration_Language()
   * @model
   * @generated
   */
  String getLanguage();

  /**
   * Sets the value of the '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getLanguage <em>Language</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Language</em>' attribute.
   * @see #getLanguage()
   * @generated
   */
  void setLanguage(String value);

  /**
   * Returns the value of the '<em><b>Compile</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compile</em>' attribute.
   * @see #setCompile(String)
   * @see org.xtext.liveprobes.liveagent.cfg.CfgPackage#getConfiguration_Compile()
   * @model
   * @generated
   */
  String getCompile();

  /**
   * Sets the value of the '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getCompile <em>Compile</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Compile</em>' attribute.
   * @see #getCompile()
   * @generated
   */
  void setCompile(String value);

  /**
   * Returns the value of the '<em><b>Command</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command</em>' attribute.
   * @see #setCommand(String)
   * @see org.xtext.liveprobes.liveagent.cfg.CfgPackage#getConfiguration_Command()
   * @model
   * @generated
   */
  String getCommand();

  /**
   * Sets the value of the '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getCommand <em>Command</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Command</em>' attribute.
   * @see #getCommand()
   * @generated
   */
  void setCommand(String value);

  /**
   * Returns the value of the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path</em>' attribute.
   * @see #setPath(String)
   * @see org.xtext.liveprobes.liveagent.cfg.CfgPackage#getConfiguration_Path()
   * @model
   * @generated
   */
  String getPath();

  /**
   * Sets the value of the '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getPath <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path</em>' attribute.
   * @see #getPath()
   * @generated
   */
  void setPath(String value);

  /**
   * Returns the value of the '<em><b>Dap</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dap</em>' attribute.
   * @see #setDap(String)
   * @see org.xtext.liveprobes.liveagent.cfg.CfgPackage#getConfiguration_Dap()
   * @model
   * @generated
   */
  String getDap();

  /**
   * Sets the value of the '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getDap <em>Dap</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dap</em>' attribute.
   * @see #getDap()
   * @generated
   */
  void setDap(String value);

  /**
   * Returns the value of the '<em><b>Parser</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parser</em>' attribute.
   * @see #setParser(String)
   * @see org.xtext.liveprobes.liveagent.cfg.CfgPackage#getConfiguration_Parser()
   * @model
   * @generated
   */
  String getParser();

  /**
   * Sets the value of the '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getParser <em>Parser</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parser</em>' attribute.
   * @see #getParser()
   * @generated
   */
  void setParser(String value);

  /**
   * Returns the value of the '<em><b>Io</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Io</em>' attribute.
   * @see #setIo(String)
   * @see org.xtext.liveprobes.liveagent.cfg.CfgPackage#getConfiguration_Io()
   * @model
   * @generated
   */
  String getIo();

  /**
   * Sets the value of the '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getIo <em>Io</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Io</em>' attribute.
   * @see #getIo()
   * @generated
   */
  void setIo(String value);

  /**
   * Returns the value of the '<em><b>Thread</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Thread</em>' attribute.
   * @see #setThread(String)
   * @see org.xtext.liveprobes.liveagent.cfg.CfgPackage#getConfiguration_Thread()
   * @model
   * @generated
   */
  String getThread();

  /**
   * Sets the value of the '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getThread <em>Thread</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Thread</em>' attribute.
   * @see #getThread()
   * @generated
   */
  void setThread(String value);

  /**
   * Returns the value of the '<em><b>Adapter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Adapter</em>' attribute.
   * @see #setAdapter(String)
   * @see org.xtext.liveprobes.liveagent.cfg.CfgPackage#getConfiguration_Adapter()
   * @model
   * @generated
   */
  String getAdapter();

  /**
   * Sets the value of the '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getAdapter <em>Adapter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Adapter</em>' attribute.
   * @see #getAdapter()
   * @generated
   */
  void setAdapter(String value);

  /**
   * Returns the value of the '<em><b>Breakpoint</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Breakpoint</em>' attribute.
   * @see #setBreakpoint(String)
   * @see org.xtext.liveprobes.liveagent.cfg.CfgPackage#getConfiguration_Breakpoint()
   * @model
   * @generated
   */
  String getBreakpoint();

  /**
   * Sets the value of the '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getBreakpoint <em>Breakpoint</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Breakpoint</em>' attribute.
   * @see #getBreakpoint()
   * @generated
   */
  void setBreakpoint(String value);

  /**
   * Returns the value of the '<em><b>Load</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Load</em>' attribute.
   * @see #setLoad(String)
   * @see org.xtext.liveprobes.liveagent.cfg.CfgPackage#getConfiguration_Load()
   * @model
   * @generated
   */
  String getLoad();

  /**
   * Sets the value of the '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getLoad <em>Load</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Load</em>' attribute.
   * @see #getLoad()
   * @generated
   */
  void setLoad(String value);

  /**
   * Returns the value of the '<em><b>Exec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exec</em>' attribute.
   * @see #setExec(String)
   * @see org.xtext.liveprobes.liveagent.cfg.CfgPackage#getConfiguration_Exec()
   * @model
   * @generated
   */
  String getExec();

  /**
   * Sets the value of the '{@link org.xtext.liveprobes.liveagent.cfg.Configuration#getExec <em>Exec</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exec</em>' attribute.
   * @see #getExec()
   * @generated
   */
  void setExec(String value);

  /**
   * Returns the value of the '<em><b>Additional Config</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Additional Config</em>' containment reference list.
   * @see org.xtext.liveprobes.liveagent.cfg.CfgPackage#getConfiguration_AdditionalConfig()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getAdditionalConfig();

} // Configuration
