/*
 * generated by Xtext 2.33.0
 */
package org.xtext.liveprobes.liveagent.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCfgScopeProvider extends DelegatingScopeProvider {
}
